### ISSUE TITLE
1.

### ISSUE THREAD

**Issue by gknpezgssb** [AlloyTeam/omix#1]
[release-v1.0.0.md中JSX vs hyperscript一节](https://github.com/AlloyTeam/omix/blob/master/tutorial/release-v1.0.0.md#jsx-vs-hyperscript)
```javascript
// JSX
<ul id="bestest-menu">
  {items.map( item =>
    <li className=".item" {...attrs(item.id)}>{item.title}</li>
  )}
</ul>
```
className=".item",item前面是不是多了一个'.'?

**Comment by dntzhang** [comment]
已修正。感谢。而且  className 可以写成 class ~~
