### ISSUE TITLE
Tag is undefined

### ISSUE THREAD

**Issue by IniZio** [AlloyTeam/omix#4]
I attempted to use omix, however when i use
```
const $ = Omi.tags
```

It gives me undefined. I search in docs but there is no documentation as for what additional steps are needed to make hyperscript work in Omix. Would be grateful if could provide some references?

**Comment by dntzhang** [comment]
the lastest version remove the hyperscript way.  please use JSX.

**Comment by IniZio** [comment]
Thanks for the info. Closing.
